### ISSUE TITLE
RFC: Roadmap for FetchCode next steps

### ISSUE THREAD

**Issue by pombredanne** [nexB/fetchcode#41]
Here are some of the TODOs and directions we could go in no specific order, based on a chat between @TG1999  and @pombredanne 

- [x] Release on PyPI
- [ ] Integration in ScanCode-toolkit such that there could be a `--from-url` option that would fetch a URL with fetchcode (but then it may also need to be extracted before being scanned....)
- [ ] ... therefore an integration in https://github.com/nexB/scancode.io/ as a "pipe" to be used in pipelines may be better?
- [ ] Add support for more API data fetching including package indexes.
- [ ] Add support for Docker images download by moving the code from https://github.com/nexB/container-inspector/tree/develop/src/container_inspector/fetch ... or create some simple plugin architecture similar to that of scancode-toolkit such that there could be plugins for various "fetchers"
- [ ] Later on an integration with an upcoming package data mining tool would be great
- [ ] **There are also some overlap between packageurl, fetchcode and scancode-toolkit packagedcode and this would benefit to be re-architected and reorged such that we have modules with clear responsibilities**
- [ ] https://github.com/nexB/dependentcode needs to be created and would be a major user of fetchcode (See https://github.com/nexB/dependentcode/issues/1 )
